#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : atk
Version  : 2.38.0
Release  : 32
URL      : https://download.gnome.org/sources/atk/2.38/atk-2.38.0.tar.xz
Source0  : https://download.gnome.org/sources/atk/2.38/atk-2.38.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0
Requires: atk-data = %{version}-%{release}
Requires: atk-lib = %{version}-%{release}
Requires: atk-license = %{version}-%{release}
Requires: atk-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : glib-dev32
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev

%description
ATK - The Accessibility Toolkit
===============================
For more information about ATK and accessibility in GNOME, see:

%package data
Summary: data components for the atk package.
Group: Data

%description data
data components for the atk package.


%package dev
Summary: dev components for the atk package.
Group: Development
Requires: atk-lib = %{version}-%{release}
Requires: atk-data = %{version}-%{release}
Provides: atk-devel = %{version}-%{release}
Requires: atk = %{version}-%{release}

%description dev
dev components for the atk package.


%package lib
Summary: lib components for the atk package.
Group: Libraries
Requires: atk-data = %{version}-%{release}
Requires: atk-license = %{version}-%{release}

%description lib
lib components for the atk package.


%package license
Summary: license components for the atk package.
Group: Default

%description license
license components for the atk package.


%package locales
Summary: locales components for the atk package.
Group: Default

%description locales
locales components for the atk package.


%prep
%setup -q -n atk-2.38.0
cd %{_builddir}/atk-2.38.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648357888
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/atk
cp %{_builddir}/atk-2.38.0/COPYING %{buildroot}/usr/share/package-licenses/atk/bf50bac24e7ec325dbb09c6b6c4dcc88a7d79e8f
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang atk10

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Atk-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/atk-1.0/atk/atk-autocleanups.h
/usr/include/atk-1.0/atk/atk-enum-types.h
/usr/include/atk-1.0/atk/atk.h
/usr/include/atk-1.0/atk/atkaction.h
/usr/include/atk-1.0/atk/atkcomponent.h
/usr/include/atk-1.0/atk/atkdocument.h
/usr/include/atk-1.0/atk/atkeditabletext.h
/usr/include/atk-1.0/atk/atkgobjectaccessible.h
/usr/include/atk-1.0/atk/atkhyperlink.h
/usr/include/atk-1.0/atk/atkhyperlinkimpl.h
/usr/include/atk-1.0/atk/atkhypertext.h
/usr/include/atk-1.0/atk/atkimage.h
/usr/include/atk-1.0/atk/atkmisc.h
/usr/include/atk-1.0/atk/atknoopobject.h
/usr/include/atk-1.0/atk/atknoopobjectfactory.h
/usr/include/atk-1.0/atk/atkobject.h
/usr/include/atk-1.0/atk/atkobjectfactory.h
/usr/include/atk-1.0/atk/atkplug.h
/usr/include/atk-1.0/atk/atkrange.h
/usr/include/atk-1.0/atk/atkregistry.h
/usr/include/atk-1.0/atk/atkrelation.h
/usr/include/atk-1.0/atk/atkrelationset.h
/usr/include/atk-1.0/atk/atkrelationtype.h
/usr/include/atk-1.0/atk/atkselection.h
/usr/include/atk-1.0/atk/atksocket.h
/usr/include/atk-1.0/atk/atkstate.h
/usr/include/atk-1.0/atk/atkstateset.h
/usr/include/atk-1.0/atk/atkstreamablecontent.h
/usr/include/atk-1.0/atk/atktable.h
/usr/include/atk-1.0/atk/atktablecell.h
/usr/include/atk-1.0/atk/atktext.h
/usr/include/atk-1.0/atk/atkutil.h
/usr/include/atk-1.0/atk/atkvalue.h
/usr/include/atk-1.0/atk/atkversion.h
/usr/include/atk-1.0/atk/atkwindow.h
/usr/lib64/libatk-1.0.so
/usr/lib64/pkgconfig/atk.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libatk-1.0.so.0
/usr/lib64/libatk-1.0.so.0.23809.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/atk/bf50bac24e7ec325dbb09c6b6c4dcc88a7d79e8f

%files locales -f atk10.lang
%defattr(-,root,root,-)

